name: Cass Operator Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    # Allow to rerun this for a tag to get updated images

jobs:
  release_ebs_csi_driver:
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/datastax/aws-ebs-csi-driver
          tags: |
            type=semver,pattern={{raw}}
      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ebs-csi-driver Docker image
        id: docker_build_ebs_csi_driver
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          target: Linux-al2023
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
